version: "1.0"
info:
  model: int-scaffold
packages:
- name: Manual_SabreenProject
  gitServerName: Sabreen_p
  gitUrl: https://github.com/Sabreen0606
  gitUsername: Sabreen0606
  gitBranch: main
- name: WmGooglePubSubProvider
  version: 12.0.0.0.9
  wpmServer: https://packages.webmethods.io
  wpmRegistry: supported
- name: WmGoogleBigQueryProvider
  version: 12.0.0.0.10
  wpmServer: https://packages.webmethods.io
  wpmRegistry: supported
- name: WmGoogleCloudStorageProvider
  version: 12.0.0.0.7
  wpmServer: https://packages.webmethods.io
  wpmRegistry: supported
- name: Punith_KMAT_Salesforce_Sync
  version: "1.0"
  gitServerName: Sabreen_shared
  gitUrl: https://github.com/karthikbm
  gitUsername: Sabreen0606
  gitBranch: main
- name: WmSalesforceProvider
  version: 12.0.0.0.23
  wpmServer: https://packages.webmethods.io
  wpmRegistry: supported
services:
- serviceName: project.manual_sabreen.WmSalesforceProvider.com_webmethods_cloudstreams_salesforce_v53.connections:TestSalesF1
  packages:
  - name: Manual_SabreenProject
    version: "1.0"
  - name: WmGooglePubSubProvider
    version: 12.0.0.0.9
  - name: WmGoogleBigQueryProvider
    version: 12.0.0.0.10
  - name: WmGoogleCloudStorageProvider
    version: 12.0.0.0.7
  - name: Punith_KMAT_Salesforce_Sync
    version: "1.0"
  - name: WmSalesforceProvider
    version: 12.0.0.0.23
- serviceName: project.manual_sabreen.integrations:TestAutoSelection1
  packages:
  - name: Manual_SabreenProject
    version: "1.0"
  - name: WmGooglePubSubProvider
    version: 12.0.0.0.9
  - name: WmGoogleBigQueryProvider
    version: 12.0.0.0.10
  - name: WmGoogleCloudStorageProvider
    version: 12.0.0.0.7
  - name: Punith_KMAT_Salesforce_Sync
    version: "1.0"
  - name: WmSalesforceProvider
    version: 12.0.0.0.23
- serviceName: project.manual_sabreen.integrations:test1
  packages:
  - name: Manual_SabreenProject
    version: "1.0"
  - name: WmGooglePubSubProvider
    version: 12.0.0.0.9
  - name: WmGoogleBigQueryProvider
    version: 12.0.0.0.10
  - name: WmGoogleCloudStorageProvider
    version: 12.0.0.0.7
  - name: Punith_KMAT_Salesforce_Sync
    version: "1.0"
  - name: WmSalesforceProvider
    version: 12.0.0.0.23
- serviceName: pub.client:http
  packages:
  - name: WmPublic
    version: 12.1.0.0.1033
