version: "1.0"
info:
  model: int-scaffold
packages:
- name: Manual_SabreenProject
  gitBranch: master
- name: WmGooglePubSubProvider
  wpmServer: https://packages.webmethods.io
  wpmRegistry: supported
- name: WmGoogleBigQueryProvider
  wpmServer: https://packages.webmethods.io
  wpmRegistry: supported
- name: WmGoogleCloudStorageProvider
  wpmServer: https://packages.webmethods.io
  wpmRegistry: supported
